--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/4/2022 16:49:44
-- Server version: 10.4.22
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE test;

--
-- Drop table `productos`
--
DROP TABLE IF EXISTS productos;

--
-- Set default database
--
USE test;

--
-- Create table `productos`
--
CREATE TABLE productos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) DEFAULT NULL,
  descripcion VARCHAR(255) DEFAULT NULL,
  precio INT(11) DEFAULT NULL,
  stock INT(11) DEFAULT NULL,
  imagen VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 27,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table productos
--
INSERT INTO productos VALUES
(26,'Ruedas darkstar 54mm', 'Ruedas darkstar violeta-blanco', 2200, 100, 'ruedas-4.jpg'), 
(21,'Ruedas darkstar 51mm', 'Ruedas darkstar multi color', 2300, 100, 'ruedas-2.jpg'), 
(22,'Ruedas darkstar 50mm', 'Ruedas darkstar turquesa', 2500, 100, 'ruedas-3.jpg'), 
(23,'Skate darkstar 8pulgadas', 'Skate darkstar maple color negro', 4000, 100, 'skate-1.jpg'), 
(24,'Skate darkstar 8.5pulgadas', 'Skate darkstar maple color azul', 4300, 100, 'skate-2.jpg'), 
(25,'Skate darkstar 7.5pulgadas', 'Skate darkstar maple color verde', 4500, 100, 'skate-3.jpg');

USE test;
CREATE TABLE usuarios (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL DEFAULT '',
  email VARCHAR(50) NOT NULL DEFAULT'',
  password VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;




-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
SELECT * FROM productos WHERE  nombre like "Rem%";